networks:
  hyperdemo_network:

volumes:
  postgres_volume:
  rabbitmq_volume:

services:
  postgresql:
    image: postgres:18.1
    container_name: hyperdemo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quazex
      POSTGRES_PASSWORD: quazex
      POSTGRES_DB: quazex
    volumes:
      - postgres_volume:/var/lib/postgresql
      - ./.docker/postgres.schema.sql:/docker-entrypoint-initdb.d/postgres.schema.sql
      - ./.docker/postgres.seeds.sql.gz:/docker-entrypoint-initdb.d/postgres.seeds.sql.gz
    networks:
      - hyperdemo_network
    ports:
      - 35432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quazex -t 10"]
      interval: 2s
      timeout: 10s
      retries: 2

  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: hyperdemo_rabbitmq
    restart: always
    ports:
      - 3556:5672
      - 3515:15672
    environment:
      RABBITMQ_DEFAULT_USER: hyperdemo
      RABBITMQ_DEFAULT_PASS: hyperdemo
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - hyperdemo_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 1s
      retries: 2
